version: "3"
services:
    cms-shelter-db:
      image: postgres
      container_name: cms_shelter_db
      restart: always
      volumes:
        - ./data/shelter/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=cms_shelter_server
        - POSTGRES_USER=shelter
        - POSTGRES_PASSWORD=20121208
      ports:
        - "5432:5432"

    cms-shelter:
        image: snslabdocker/cms_main
        container_name: cms_shelter
        depends_on:
          - cms-shelter-db
        restart: always
        #command: sh -c "/bin/bash start_cms.sh"
        command: /bin/bash -c "while true; do echo test; sleep 100; done"
        ports:
          - "8000:8000"



    # cms-shelter:
    # cms-shelter-db: