version: "3"
services:
    cms-main:
        image: snslabdocker/cms_main
        container_name: cms_main
        depends_on:
          - cms-main-db
        restart: always
        command: sh -c "/bin/bash start_cms.sh"
        ports:
          - "8000:8000"

    cms-main-db:
        image: postgres
        container_name: cms_main_db
        restart: always
        volumes:
          - ./data/postgres:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=cms_main_server
          - POSTGRES_USER=main
          - POSTGRES_PASSWORD=20121208
        ports:
          - "5432:5432"

    # cms-shelter:
    # cms-shelter-db: